<a href="https://colab.research.google.com/github/yagnikta/numpy_basics/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [ ]:
ar = np.array([1,2,3])

In [ ]:
print(ar.ndim)

1


In [ ]:
ar = np.array(332)

In [ ]:
print(ar.ndim)

0


In [ ]:
a = np.array([])
a.ndim

1

In [ ]:
range = np.arange(1, 10, 2)
print(range)

[1 3 5 7 9]


In [ ]:
ar = np.linspace(0,1,7)
ar

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [ ]:
ar = np.logspace(1,5,6)
ar

array([1.00000000e+01, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04, 1.00000000e+05])

In [ ]:
ar = np.zeros(5)
ar

array([0., 0., 0., 0., 0.])

In [ ]:
ar = np.zeros(4)
ar2 = np.zeros((4))
print(ar, ar2)

[0. 0. 0. 0.] [0. 0. 0. 0.]


In [ ]:
ar = np.ones((2,2), dtype=int)
ar

array([[1, 1],
       [1, 1]])

In [ ]:
ar = np.full((2,8), 1)
ar

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
ar = np.empty([9,2])
ar

array([[ 4.43019308e-315,  0.00000000e+000],
       [ 9.23406358e-305, -2.54779384e+078],
       [ 5.58770407e-111, -3.06835199e-231],
       [ 4.72049105e-242,  1.33778311e-197],
       [-2.04038657e+097,  1.52109540e-308],
       [ 1.18206253e-168,  7.73577096e-239],
       [-3.36353955e+231,  3.64674657e-304],
       [ 3.97370997e+255,  1.10413978e-316],
       [ 0.00000000e+000,  0.00000000e+000]])

In [ ]:
ar = np.random.rand(2,2)
ar

array([[0.86625197, 0.62167058],
       [0.64258978, 0.33235432]])

In [ ]:
ar = np.random.randn(3,4) #random floats from normal distribution, mean = 0, deviation = 1

4.09326799577477


In [ ]:
ar = np.random.randint(10, 100, (10,5)) # start, stop, number of values
ar

array([[58, 45, 59, 69, 87],
       [22, 15, 94, 51, 67],
       [84, 80, 20, 74, 59],
       [35, 66, 72, 44, 17],
       [47, 55, 38, 69, 59],
       [83, 48, 38, 76, 88],
       [13, 98, 22, 18, 81],
       [34, 82, 75, 12, 98],
       [36, 79, 67, 41, 40],
       [95, 58, 80, 36, 47]])

In [ ]:
ar = np.array([1.1, 2.3, 're'])
print(type(ar), ar.dtype) # type shows class, and dtype shows datatype

<class 'numpy.ndarray'> <U32


In [ ]:
ar = np.array([1,2,3,4], dtype=np.uint32)
ar

array([1, 2, 3, 4], dtype=uint32)

In [ ]:
ar = np.array([1,2,3,4]).astype(np.int32)
ar

array([1, 2, 3, 4], dtype=int32)

In [ ]:
ar = np.array([
      [
        [21],[12]
      ],
      [
        [22],[22]
      ]
    ])
print(
' dimensions of array: ',ar.shape, '\n',
'number of elements present in array: ',ar.size, '\n',
'Item size of array: ', ar.itemsize
)

 dimensions of array:  (2, 2, 1) 
 number of elements present in array:  4 
 Item size of array:  8


In [ ]:
# Reshape

ar = np.array([1,2,3,4,5,6,7,8])
reshaped = ar.reshape(2,2,2)
print(reshaped)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Flatten

ar = np.array([
    [1,2,3],
    [4,5,6]
])

flat = ar.flatten()
print(flat)

[1 2 3 4 5 6]


In [ ]:
# Ravel

ar = np.array([
    [1,2,3],
    [4,5,6]

])

raveled = ar.ravel()
print(raveled)

[1 2 3 4 5 6]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(b / a)
print(b // a)
print(b % a)
print(a ** b)

[ 4  6  8 10]
[-2 -2 -2 -2]
[ 3  8 15 24]
[3.         2.         1.66666667 1.5       ]
[3 2 1 1]
[0 0 2 2]
[   1   16  243 4096]


In [ ]:
# Square root
arr = np.array([1,4,9,16,25]).astype(np.int64)
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [ ]:
# Exponential

print(np.exp([0,1,2]))

[1.         2.71828183 7.3890561 ]


In [ ]:
# Sine values:

angles = np.array([0, np.pi/6, np.pi/3, np.pi/2, np.pi])
print(np.sin(angles))

[0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 1.22464680e-16]


**Indexing and Slicing**

In [ ]:
a = np.array([1,2,3,4,5])

print(a[0:5:3])

[1 4]


In [ ]:
ar = a[::-1]
ar

array([5, 4, 3, 2, 1])

In [ ]:
a[1::2]

array([2, 4])

**Multi Dimensional Slicing**

In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix[1:, 1:])

[[5 6]
 [8 9]]


* np.take -> built in function to perform indexing and slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7,4,4,3])
ind = [1,9]

print(np.take(arr, ind))

[2 3]


**To Iterate through numpy array we use np.nditer**

In [ ]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 5 6 7 4 4 3 

**To Iterate through numpy array having access to indexes we use ndenumerate**

In [ ]:
a = np.array([
    [1,2],
    [3,4]
])

for ind, x in np.ndenumerate(a):
  print(ind, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
# Views vs Copies

arr = np.array([1,2,3,4,5])

view = arr[1:3] # passed by reference

copy = arr[1:3].copy() # passed by value

arr[1] = 0

print(view, copy)

[0 3] [2 3]


**Transpose of a Matrix**

In [ ]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
arr.transpose()

[[1 2]
 [3 4]]


In [10]:
ar1 = np.array([
    [1,2],
    [3,4]
])

ar2 = np.array([
    [5, 6],
    [7,8]
])
print(np.vstack((ar1, ar2)))
print(np.hstack((ar1, ar2)))
print(np.stack((ar1, ar2), axis = 0))
print(np.stack((ar1, ar2), axis = 1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [16]:
ar = np.array([1,2,3,4,5,6])
print(np.repeat(ar, 2), np.tile(ar, 2))

[1 1 2 2 3 3 4 4 5 5 6 6] [1 2 3 4 5 6 1 2 3 4 5 6]


In [18]:
print('sum: ', np.sum(ar))
print('min: ', np.min(ar))
print('max: ', np.max(ar))
print('mean: ', np.mean(ar))
print('median: ', np.median(ar))
print('std: ', np.std(ar))
print('variance: ', np.var(ar))

sum:  21
min:  1
max:  6
mean:  3.5
median:  3.5
std:  1.707825127659933
variance:  2.9166666666666665


In [21]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.sum(matrix, axis = 0))

[12 15 18]


In [42]:
ar = np.array([10,20,30,40])

print(np.cumsum(ar))
print(np.cumprod(ar))

[ 10  30  60 100]
[    10    200   6000 240000]


In [30]:
ar

array([1, 2, 3, 4])

In [37]:
res = np.where(ar <= 3)
print(res)

(array([0, 1, 2]),)


In [39]:
res = (np.argwhere(ar > 0)) # returns the indices
print(res)

[[0]
 [1]
 [2]
 [3]]


In [43]:
mask = np.logical_and(ar > 15, ar < 35)
mask

array([False,  True,  True, False])

In [50]:
mask = np.logical_and(matrix > 3, matrix < 9)
mask_or = np.logical_or(matrix > 3, matrix < 9)
print(mask, '\n' , mask_or)

[[False False False]
 [ True  True  True]
 [ True  True False]] 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [48]:
res = np.argwhere(matrix > 4) # returns the indices
print(res)

[[1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]


In [53]:
res = np.nonzero(ar)
resmat = np.nonzero(matrix)
print(res, '\n', resmat)

(array([0, 1, 2, 3]),) 
 (array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


**Broadcasting in Numpy (IMP)**

* If shapes are equal, they're compatible.
* If one is 1 (shape), it can be stretched to match the other
* If shapes are different and not 1 or equal -> x error

In [54]:
image = np.array([
    [100, 150],
    [200, 250]
])

brightness = image + 50

print(brightness) # This will broadcast the scalar 50 to the shape of image(Rule 1)

[[150 200]
 [250 300]]


**Vectorization**
* To implement a custom function in numpy

In [55]:
def square(x):
    return x*x

vfunc = np.vectorize(square)

In [56]:
ar = [1,2,3,4,5,6,7]
print(vfunc(ar))

[ 1  4  9 16 25 36 49]


**Dealing with Missing Values**

In [58]:
a = np.array([1, 2, np.inf, 4])
a

# np.inf and -np.inf -> positive and negative infinites

array([ 1.,  2., inf,  4.])

In [64]:
ar = np.array([1, 2, 3, np.nan, np.inf, -np.inf])
print(np.isnan(ar)) # checks for nan values
print(np.isinf(ar)) # checks for infinite values
print(np.isfinite(ar)) # checks for finite values

[False False False  True False False]
[False False False False  True  True]
[ True  True  True False False False]


* To replace the non values we use the following functions

In [65]:
new_ar = np.nan_to_num(ar, nan = 0, posinf = 1, neginf = -1)
new_ar

array([ 1.,  2.,  3.,  0.,  1., -1.])